// ... earlier code ...

// Remove synchronous generateIntelligentFallback function here
// function generateIntelligentFallback(...) {
//    ...
// }

// Keep the async version of the generateIntelligentFallback function
async function generateIntelligentFallback(...) {
    ...
}

// ... later code ...