name: Run Gemini CLI

# This workflow will also create a pull request for any changes made by the workflow

on:
  workflow_dispatch:

jobs:
  run-gemini:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Gemini CLI to generate code
        uses: google-github-actions/run-gemini-cli@v0.1.12
        with:
          args: "generate --output generated_code.js --prompt 'Create a function that returns the sum of two numbers.'"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated changes from Gemini CLI"
          title: "Automated PR from Gemini CLI"
          body: "This pull request was created automatically by the workflow."
          branch: "gemini-auto-pr"
